name: Translate README

on:
  push:
    paths:
      - 'README.md'  # Sproži akcijo ob spremembi README.md

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Uporabi različico .NET Core, ki ustreza tvojemu prevajalskemu programu

    - name: Install dependencies
      run: dotnet restore  # Če tvoj projekt uporablja NuGet pakete, jih bo to obnovilo

    - name: Run translation program
      run: |
        # Tu lahko prilagodiš klic svojega prevajalskega programa
        # Predpostavljamo, da imaš C# aplikacijo, ki prevaja README.md
        dotnet run --project D:/Barbara/Prevedi.exe README.md

    - name: Commit translated files
      run: |
        git config --global user.name 'JureBrlogar'
        git config --global user.email 'jure.brlogar@gmail.com'
        git add README.*.md
        git commit -m "Automated translation of README.md"
        git push
